hello:
	gcc -pthread hello.c -o hello
	./hello

func:
	gcc -pthread func.c -o func
	./func

cond:
	gcc -pthread cond.c -o cond
	./cond

randomsearch:
	gcc -pthread randomsearch.c -o random

sumR:
	gcc -pthread sumR.c -o sum
	./sum

clean:
	rm -f *.o
	rm hello
	rm func
	rm -f cond
	rm program2


